name: Backend CI

on:
  push:
    branches:
      - "*"

defaults:
  run:
    working-directory: step

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon